# default.conf
# --------------------------------------------------------
# Configuración específica de servidor (virtual host).
# Escucha en HTTPS (puerto 443), sirve WordPress estatico desde
# /var/www/html y reenvía peticiones dinamicas PHP al contenedor 
# WordPress en el puerto 9000. También maneja certificados 
# SSL autofirmados y reglas básicas de seguridad.
# --------------------------------------------------------

server {
    listen 443 ssl; # Escucha solo en 443 y con ssl
    server_name jocuni-p.42.fr; # Incluyo aqui porque solo voy a usar este dominio en todo el proyecto

#	Ubicacion de los certificados
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

#	Conf standard para WordPress
    root /var/www/html; # Directorio donde esta el contenido estatico que servira nginx cuando se llame a jocuni-p.42.fr
    index index.php index.html index.htm; # Orden de busqueda para archivos index

#	Sirve contenido estatico y canaliza las peticiones dinamicas (PHP) al contenedor wordpress
#	nginx lo intentara servir como archivo, si no existe lo buscara como directorio,
#	si no lo encontro redirigira la solicitud a php. 
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

#	 Si una peticion termina en .php la reenvia al contenedor de WordPress en puerto 9000
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

#	Proteccion. Bloquea acceso a cualquier cliente que solicite archivos tipo .ht*
#	porque son usados para informacion sensible.
    location ~ /\.ht {
        deny all;
    }
}
