# nginx.conf
# --------------------------------------------------------
# Archivo de configuración global de NGINX.
# Define parámetros globales como procesos, conexiones,
# configuración SSL, logs y carga de archivos adicionales 
# (como default.conf) desde /etc/nginx/conf.d/.
# --------------------------------------------------------

# Usa todos los cores disponibles de la maquina, para aprovechar recursos
worker_processes auto;

events {
	# Establece el maximo de conexiones simultaneas por worker (1024 adecuado para mi proyecto)
    worker_connections 1024;
}

http {
	#conf standard y necesaria para reconocer extensiones de archivos
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Establece los parametros de conf SSL
	ssl_protocols TLSv1.3;                 # Solo TLS 1.3 (lo más moderno)
	ssl_ciphers HIGH:!aNULL:!MD5;          # Cifrados fuertes, excluye los inseguros
	ssl_prefer_server_ciphers on;          # Nosotros decidimos qué cifrado usar
	ssl_session_timeout 1d;                # Cache de sesiones por 1 día
	ssl_session_cache shared:SSL:10m;      # 10MB de cache para sesiones

    # Redirige los logs de salida y de error a consola (facilita depuracion con docker logs)
	access_log /dev/stdout;
	error_log /dev/stderr;

	# Directiva para que cargue configuraciones adicionales (como default.com con la conf especifica de mi wordpress)
    include /etc/nginx/conf.d/*.conf;
}
