# Configura tantos workers como CPUs tenga el servidor, para aprovechar recursos
worker_processes auto;

events {
	# Establece el maximo de conexiones simultaneas por worker (1024 adecuado para mi proyecto)
    worker_connections 1024;
}

http {
	#conf standard y necesaria para reconocer extensiones de archivos
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # SSL Configuration
	ssl_protocols TLSv1.3;                 # Solo TLS 1.3 (lo más moderno)
	ssl_ciphers HIGH:!aNULL:!MD5;          # Cifrados fuertes, excluye los inseguros
	ssl_prefer_server_ciphers on;          # Nosotros decidimos qué cifrado usar
	ssl_session_timeout 1d;                # Cache de sesiones por 1 día
	ssl_session_cache shared:SSL:10m;      # 10MB de cache para sesiones

    # Deriva los logs a stdout y stderr que a su vez el Dockerfile redirige a Docker
	access_log /dev/stdout;
	error_log /dev/stderr;

	# Directiva para que cargue todos los files .conf (como default.com con la conf de mi wordpress)
	# de este modo combinara ambas configuraciones al iniciar nginx
    include /etc/nginx/conf.d/*.conf;
}